services:
  frontend_proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend_load_balancer

  backend_load_balancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend_load_balancer.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend_container_1
      - backend_container_2

  backend_container_1:
    image: devhub-backend-container
    ports:
      - "81:80"

  backend_container_2:
    image: devhub-backend-container2
    ports:
      - "82:80"

networks: 
  my-network:
    driver: bridge
