name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4  
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t devhub3/devhub-frontend .
      - name: Publish image to docker hub
        run: docker push devhub3/devhub-frontend:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2-frontend]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull devhub3/devhub-frontend:latest
      - name: Delete old container
        run: sudo docker rm -f devhub-frontend-container
      - name: Run docker container
        run: sudo docker run -d -p 5000:5000 --name devhub-frontend-container devhub3/devhub-frontend